name: Build

# manually trigger
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    # setup
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - uses: microsoft/setup-msbuild@v1.0.2
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Download premake5
      run: |
        curl.exe -o premake5.zip -L https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-windows.zip
        tar -xf premake5.zip

    - name: Download libraries
      run: |
        curl -o lib.zip https://files.theindra.eu/files/lib.zip
        tar -xf lib.zip

    - name: Generate project files
      run: .\premake5 vs2019

    # compile
    - name: Build Anniversary
      run: MSBuild /p:Configuration=Release /p:Platform=TRAE

    - name: Build Underworld
      run: MSBuild /p:Configuration=Release /p:Platform=TR8

    - name: Build Legend
      run: MSBuild /p:Configuration=Release /p:Platform=TR7

    - name: Build Legend Nextgen Demo
      run: MSBuild /p:Configuration=Release /p:Platform=TR7DEBUG

    # upload
    - uses: actions/upload-artifact@v2
      with:
        name: Anniversary
        path: |
          bin/TRAE/Release/TRAE-Menu-Hook.asi
          bin/TRAE/Release/TRAE-Menu-Hook.pdb

    - uses: actions/upload-artifact@v2
      with:
        name: Underworld
        path: |
          bin/TR8/Release/TR8-Menu-Hook.asi
          bin/TR8/Release/TR8-Menu-Hook.pdb

    - uses: actions/upload-artifact@v2
      with:
        name: Legend
        path: |
          bin/TR7/Release/TR7-Menu-Hook.asi
          bin/TR7/Release/TR7-Menu-Hook.pdb

    - uses: actions/upload-artifact@v2
      with:
        name: Legend Nextgen Demo
        path: |
          bin/TR7DEBUG/Release/TR7DEBUG-Menu-Hook.asi
          bin/TR7DEBUG/Release/TR7DEBUG-Menu-Hook.pdb
